# Generated by Django 5.0.1 on 2024-01-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallets',
            name='type',
            field=models.CharField(choices=[('Visa', 'visa'), ('Mastercard', 'mastercard')], max_length=10),
        ),
    ]
