# Generated by Django 5.0.1 on 2024-01-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_alter_wallets_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallets',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='wallets',
            name='name',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
