# Generated by Django 5.0.1 on 2024-01-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0006_alter_wallets_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallets',
            name='name',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
